wandb_version: 1

epochs:
  desc: null
  value: 100
task:
  desc: null
  value: reward
environment:
  desc: null
  value: sac_ant
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1694716843.383888
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      - 24
      4: 3.10.12
      5: 0.15.10
      8:
      - 5
